config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :admins

  root to:"home#current"

  post 'assemblies' , to: 'assemblies#create', as: "assemblies_create"

  resources :books

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
    enum status: ["free","reserved", "bought"]
    has_many :assemblies
    has_many :users, through: :assemblies, dependent: :destroy
    accepts_nested_attributes_for :assemblies, reject_if: :all_blank, allow_destroy: true

    
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :set_book, only: %i[show edit update destroy ]
    before_action :set_statuses, only: %i[edit new]
    
      def index
        @books = Book.all
      end
      
      def new
        @book = Book.new
      end

      def show
      end
      
      
      def create
        @books = Book.all
        @book = Book.new(book_params)
        respond_to do |format|
          if @book.save
            format.js {render nothing: true, notice: 'Lo re creaste'}
          end
        end
      end
    
      def edit
        
      end
      
    
      def update
        respond_to do |format|
          if @book.update(book_params)
            format.js { render nothing: true, notice: "La buena actualizada" }
            format.json { render :show, status: :created, location: @book }
          end
        end
      end
      
      def destroy
        @book.destroy
        respond_to do |format|
          format.js { render nothing: true, notice: 'Esto nunca paso' }
        end
      end
    
      private

      def set_statuses
        @statuses = Book.statuses.keys
      end

      def set_book
        @book = Book.find(params[:id])
      end
    
      def book_params
        params.require(:book).permit(:title, :author, :status, :price, :loan_date, :return_date)
      end


    # before_action :set_book, only: %i[ show edit update destroy ]
    # before_action :set_statuses, only: %i[edit new]
  
    # # GET /books or /books.json
    # def index
      
    #   if params[:search]
    #       if params[:search] == 'On_shelf'
    #         params[:search] = 1
    #         @bookses = Book.where('status = ?', params[:search])
    #       elsif params[:search] == 'Borrow'
    #         params[:search] = 0
    #         @bookses = Book.where('status = ?', params[:search])
    #       else 
    #         redirect_to books_path notice: 'El dato ingresado no es correcto'
    #       end
  
    #   elsif params[:sort] == 'title'
    #     @bookses = Book.order(params[:sort])
    #   else 
    #     @bookses = Book.all
    #   end
  
      
    #   # if params[:q]
    #   #   if params[:q] == 'On_shelf'
    #   #     params[:q] = 1
    #   #   elsif params[:q] == 'Borrow'
    #   #     params[:q] = 0
    #   #   else 
    #   #     redirect_to books_path notice: 'El dato ingresado no es correcto'
    #   #   end
    #   #   @books = Book.where('status = ?', params[:q])
        
    #   #   if @books.nil?
    #   #     @books = Book.all
    #   #   end
    #   # else
    #   #   @books = Book.all
    #   # end
  
    #   # @bookses = Book.order(params[:sort])
  
    # end
  
    # # GET /books/1 or /books/1.json
    # def show
    # end
  
    # # GET /books/new
    # def new
    #   @book = Book.new
    # end
  
    # # GET /books/1/edit
    # def edit
    # end
  
    # # POST /books or /books.json
    # def create
      
    #   @book = Book.new(book_params)
  
    #   if @book.nil?
    #     format.html { render :new, status: :unprocessable_entity }
    #   end
  
    #   respond_to do |format|
    #     if @book.save
    #       format.html { redirect_to @book, notice: "Book was successfully created." }
    #       format.json { render :show, status: :created, location: @book }
    #     else
    #       format.html { render :new, status: :unprocessable_entity }
    #       format.json { render json: @book.errors, status: :unprocessable_entity }
    #     end
    #   end
    # end
  
    # # PATCH/PUT /books/1 or /books/1.json
    # def update
    #   respond_to do |format|
    #     if @book.update(book_params)
    #       format.html { redirect_to @book, notice: "Book was successfully updated." }
    #       format.json { render :show, status: :ok, location: @book }
    #     else
    #       format.html { render :edit, status: :unprocessable_entity }
    #       format.json { render json: @book.errors, status: :unprocessable_entity }
    #     end
    #   end
    # end
  
    # # DELETE /books/1 or /books/1.json
    # def destroy
    #   @book.destroy
    #   respond_to do |format|
    #     format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
    #     format.json { head :no_content }
    #   end
    # end
  
    # private
  
    # def set_statuses
    #   @statuses = Book.statuses.keys
    # end
    #   # Use callbacks to share common setup or constraints between actions.
    #   def set_book
    #     @book = Book.find(params[:id])
    #   end
  
    #   # Only allow a list of trusted parameters through.
    #   def book_params
    #     params.require(:book).permit(:title, :author, :status, :loan_date, :return_date)
    #   end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_books.html.erb
<% @books.each do |book| %>
  <% if book.status != 'reserved'%>
    <tr>
      <td><%= best_in_place book, :title %></td> 
      <td><%= best_in_place book, :author %></td>
      <td><%= best_in_place book, :status %></td>
      <td><%= best_in_place book, :price %></td>
      <td><%= best_in_place book, :loan_date %></td> 
      <td><%= best_in_place book, :return_date %></td>
      <td><%= link_to "Reservar",  assemblies_create_path(book_id: book.id ) , method: :post%> </td> 
      <td><%= link_to 'Show', book, remote: true, class: "btn btn-info" %></td>
      <td><%= link_to 'Editar', edit_book_path(book.id), remote: true %></td>
      <td><%= link_to 'Destroy', book, data: {confirm: 'Seguro?'}, method: :delete, remote: true %></td>
    </tr>
  <% end %>
<% end %>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title  %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, options_for_select(@statuses) %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>
  
  <div class="field">
    <%= form.label :loan_date %>
    <%= form.date_select :loan_date %>
  </div>

  <div class="field">
    <%= form.label :return_date %>
    <%= form.date_select :return_date %>
  </div>

  <div class = 'actions'>
    <%= form.submit data: { disable_with: 'Creado...' } %>
  </div>
<% end %>

app/views/books/create.js.erb
$('#my_books').append("<%= escape_javascript render('books/books', book: @book) %>");
$('#myForm').html(" "); 

app/views/books/destroy.js.erb
console.log("#book_<%= @book.id %>")
$("#book_<%= @book.id%>").remove(); 

app/views/books/edit.js.erb
$('#myForm').append("<%= escape_javascript render('books/form', book: @book) %>")

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center mb-5">Books</h1>


<div class="container">

<table class = "table">
  <thead>
    <tr>
        <th>Title</th>
        <th>Author</th>
        <th>Status</th>
        <th>Price</th>
        <th>Loan date</th>
        <th>Return date</th>
        <th colspan="4"></th>
    </tr>
  </thead>

  <tbody id="my_books">
      <%= render('books/books') %>
  </tbody>
</table>

  <br>
  <%= link_to 'New Book', new_book_path, remote: true , class: "btn btn-primary"%>

  <div id="myForm" class = "my-5"></div>

  <div id="showData"></div>
</div>

app/views/books/index.js.erb
$("#data").html("<%=escape_javascript(render partial: 'books/books', @books => @books)%>")

app/views/books/new.html.erb
<h1>New Nook</h1>

<%= render 'form', book: @book %>
<%= link_to 'Back', books_path %>

app/views/books/new.js.erb
$("#myForm").html("<%= escape_javascript render('books/form', book:@book) %>")

app/views/books/show.js.erb
$("#showData").html("<%= escape_javascript render('books/show') %>")

app/views/books/update.js.erb
$('#myForm').empty()
$("#book_<%= @book.id %>").replaceWith("<%= j render('books/books', book: @book) %>")
$('#myForm').empty()